# Generated by Django 2.0 on 2018-02-07 06:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Asset Name', max_length=255, unique=True)),
                ('hostname', models.CharField(help_text='Asset hostname', max_length=4096, unique=True)),
                ('description', models.TextField(blank=True, help_text='Extended details')),
                ('asset_tag', models.CharField(help_text='Asset tag', max_length=4096, unique=True)),
                ('org_asset_tag',
                 models.CharField(help_text="Asset id from salesforce org's asset object", max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallHardware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hardware Name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Extended details')),
                ('one_gbe_interface_count',
                 models.IntegerField(default=None, help_text='Number of 1GbE interfaces', null=True)),
                ('ten_gbe_interface_count',
                 models.IntegerField(default=None, help_text='Number of 10GbE interfaces', null=True)),
                ('ram_gb', models.IntegerField(default=None, help_text='Amount of installed RAM in GiB', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallHardwareClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hardware Class Name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Extended details')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalFWInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ifname', models.CharField(help_text='Interface name', max_length=255)),
                ('netmask', models.GenericIPAddressField(default=None, help_text="Interface's netmask")),
                ('ip', models.GenericIPAddressField(help_text='IPv4 Address')),
                ('firewall', models.ForeignKey(help_text='Firewall this interface belongs to',
                                               on_delete=django.db.models.deletion.CASCADE, to='pfsense.Firewall')),
            ],
        ),
        migrations.CreateModel(
            name='PortGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Port group name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Extended details')),
            ],
        ),
        migrations.CreateModel(
            name='TUPort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Port common name', max_length=255)),
                ('proto',
                 models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', help_text='IP Protocol',
                                  max_length=3)),
                ('port', models.IntegerField(default=None, help_text='TCP or UDP port number')),
            ],
        ),
        migrations.AddField(
            model_name='portgroup',
            name='ports',
            field=models.ManyToManyField(to='pfsense.TUPort'),
        ),
        migrations.AddField(
            model_name='firewallhardware',
            name='hwclass',
            field=models.ForeignKey(help_text='Base hardware', on_delete=django.db.models.deletion.CASCADE,
                                    to='pfsense.FirewallHardwareClass'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='hw',
            field=models.ForeignKey(help_text='Base hardware', on_delete=django.db.models.deletion.CASCADE,
                                    to='pfsense.FirewallHardware'),
        ),
    ]
